# Generated by Django 3.1.2 on 2020-11-02 20:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='tenant_det',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_flatno', models.IntegerField()),
                ('tenant_first_name', models.CharField(max_length=100)),
                ('tenant_last_name', models.CharField(max_length=100)),
                ('tenant_email', models.EmailField(max_length=100)),
                ('tenant_phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+911234567890'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('tenant_dob', models.DateField(blank=True, null=True)),
                ('tenant_occupied', models.BooleanField(default=False)),
                ('tenant_permnt_addr1', models.CharField(max_length=100)),
                ('tenant_permnt_addr2', models.CharField(max_length=100)),
                ('tenant_permnt_city', models.CharField(max_length=100)),
                ('tenant_permnt_state', models.CharField(max_length=100)),
                ('tenant_permnt_country', models.CharField(max_length=100)),
                ('tenant_permnt_pincode', models.IntegerField()),
                ('tenant_police_verification', models.BooleanField(default=False)),
                ('tenant_occupy_date', models.DateTimeField(auto_now_add=True)),
                ('tenant_vacate_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='owner_det',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_flatno', models.IntegerField()),
                ('owner_first_name', models.CharField(max_length=100)),
                ('owner_last_name', models.CharField(max_length=100)),
                ('owner_email', models.EmailField(max_length=100)),
                ('owner_phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+911234567890'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('owner_dob', models.DateField(blank=True, null=True)),
                ('owner_occupied', models.BooleanField(default=False)),
                ('owner_comm_addr1', models.CharField(max_length=100)),
                ('owner_comm_addr2', models.CharField(max_length=100)),
                ('owner_comm_city', models.CharField(max_length=100)),
                ('owner_comm_state', models.CharField(max_length=100)),
                ('owner_comm_country', models.CharField(max_length=100)),
                ('owner_comm_pincode', models.IntegerField()),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
