# Generated by Django 3.1.2 on 2020-11-10 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0003_auto_20201104_0024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant_det',
            name='tenant_occupied',
        ),
    ]
