# Generated by Django 3.1.2 on 2020-11-10 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0004_remove_tenant_det_tenant_occupied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant_det',
            name='tenant_occupy_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tenant_det',
            name='tenant_vacate_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
