# Generated by Django 3.1.2 on 2020-11-10 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0005_auto_20201110_0808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner_det',
            old_name='owner_occupied',
            new_name='tenant_occupied',
        ),
    ]
